### ISSUE TITLE
contentSize null in Viewport

### ISSUE THREAD

**Issue by UbiCue** [altert/OpenSeadragonCanvasOverlay#2]
When calling canvasOverlay to add an overlay to the viewer, I received an error "Cannot read property 'x' of null" for line 95 of openseadragon-canvas-overlay.js: 
this.imgWidth = this._viewer.viewport.contentSize.x;
In the current OpenSeadragon documention, I could not find a member "contentSize" in Viewport. I changed the imgWidth definition to:
this.imgWidth = this._viewer.source.dimensions.x;
with a similar change to imgHeight, and it appears to be working properly. Is this a better approach or did I do something wrong in setting up the viewer before calling canvasOverlay()?

**Comment by altert** [comment]
viewport.contentSize was dropped in OpenSeadragon 2.2.0. I've updated plugin accordingly, thanks. Your direction was right)
